/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author PC
 */
public class SavePanel extends javax.swing.JPanel {
    /**
     * Creates new form SavePanel
     *
     */
    public SavePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveByEncrypted = new javax.swing.JButton();
        saveByCard = new javax.swing.JButton();

        saveByEncrypted.setText("Save by Encryption");

        saveByCard.setText("Save by Card Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveByEncrypted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(saveByCard)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveByEncrypted)
                    .addComponent(saveByCard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getSaveByCard(){
        return saveByCard;
    }
    
    public JButton getSaveByEncrypted(){
        return saveByEncrypted;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton saveByCard;
    private javax.swing.JButton saveByEncrypted;
    // End of variables declaration//GEN-END:variables
}
